-- MySQL Script generated by MySQL Workbench
-- Mon Mar  2 14:08:07 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Данные_Банка
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Данные_Банка
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Данные_Банка` DEFAULT CHARACTER SET utf8 ;
USE `Данные_Банка` ;

-- -----------------------------------------------------
-- Table `Данные_Банка`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Данные_Банка`.`clients` (
  `client_id` INT NOT NULL AUTO_INCREMENT,
  ` registration_date` DATE NOT NULL,
  `segment` VARCHAR(45) NOT NULL,
  `region` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`client_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Данные_Банка`.`transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Данные_Банка`.`transactions` (
  `transaction_id` INT NOT NULL AUTO_INCREMENT,
  `client_id` INT NOT NULL,
  `transaction_date` DATE NOT NULL,
  `product_type` VARCHAR(45) NOT NULL,
  `amount` FLOAT NOT NULL,
  `revenue` FLOAT NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`transaction_id`),
  INDEX `client_idx` (`client_id` ASC) VISIBLE,
  CONSTRAINT `client`
    FOREIGN KEY (`client_id`)
    REFERENCES `Данные_Банка`.`clients` (`client_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
